apiVersion: v1
kind: Template
metadata:
  name: {{ os }}-{{ item.workload }}-{{ item.flavor }}
  annotations:
    openshift.io/display-name: "Red Hat Enterprise Linux 7.0+ VM"
    description: >-
      This template can be used to create a VM suitable for
      Red Hat Enterprise Linux 7 and newer. This template
      can also be used for CentOS based VMs.
      The template assumes that a PVC is available which is providing the
      necessary RHEL disk image.
    tags: "kubevirt,virtualmachine,linux,rhel"

{% include "_linux.yaml" %}

