sudo: required
dist: xenial
language: python
branches:
  only:
  - master
  - /^v[0-9]/
env:
  global:
  - CPLATFORM=minishift
jobs:
  include:
  - stage: Tests
    name: Check syntax of all templates
    env: TARGET=syntax-tests
    script: bash -x test.sh

  - name: Functional test of the Fedora template
    env: TARGET=functional-tests TEST_FUNCTIONAL="fedora-desktop-tiny fedora-desktop-small fedora-desktop-medium fedora-desktop-large"
    script: bash -x test.sh

  - name: Functional test of the Ubuntu template
    env: TARGET=functional-tests TEST_FUNCTIONAL="ubuntu-desktop-tiny ubuntu-desktop-small ubuntu-desktop-medium ubuntu-desktop-large"
    script: bash -x test.sh

  - name: Functional test of the CentOS 8 template
    env: TARGET=functional-tests TEST_FUNCTIONAL="centos8-server-tiny centos8-server-small centos8-server-medium centos8-server-large"
    script: bash -x test.sh

  - name: Functional test of the desktop CentOS 8 template
    env: TARGET=functional-tests TEST_FUNCTIONAL="centos8-desktop-tiny centos8-desktop-small centos8-desktop-medium centos8-desktop-large"
    script: bash -x test.sh

  - name: Functional test of the CentOS 7 template
    env: TARGET=functional-tests TEST_FUNCTIONAL="centos7-server-tiny centos7-server-small centos7-server-medium centos7-server-large"
    script: bash -x test.sh

  - name: Functional test of the desktop CentOS 7 template
    env: TARGET=functional-tests TEST_FUNCTIONAL="centos7-desktop-tiny centos7-desktop-small centos7-desktop-medium centos7-desktop-large"
    script: bash -x test.sh

  - name: Functional test of the CentOS 6 template
    env: TARGET=functional-tests TEST_FUNCTIONAL="centos6-server-tiny centos6-server-small centos6-server-medium centos6-server-large"
    script: bash -x test.sh

  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    before_script: skip
    # released artifacts MUST always have REVISION=1
    script: make release "VERSION=$TRAVIS_TAG" REVISION=1
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      file: dist/common-templates-$TRAVIS_TAG.yaml
      skip_cleanup: true
      name: $TRAVIS_TAG
      on:
        tags: true
        repo: kubevirt/common-templates

cache:
  directories:
  - cache
  - "~/.minishift/cache"
  - "~/.minikube/cache"
addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    packages:
    - qemu-utils
    - jq
    - ansible
    - python-gobject
    - libosinfo-1.0
    - gir1.2-libosinfo-1.0
    - intltool
before_script:
- sudo mount --make-rshared /
- bash -x ci/ci/extra/get-kubevirt-releases
- bash -x ci/prepare-host $CPLATFORM
- bash -x ci/prepare-host virtctl $(bash -x ci/ci/extra/cat-kubevirt-release last)
- bash -x ci/start-cluster $CPLATFORM
- bash -x ci/deploy-kubevirt $CPLATFORM
before_deploy:
- openssl aes-256-cbc -K $encrypted_02d89e1b05ff_key -iv $encrypted_02d89e1b05ff_iv -in ssp-operator-deploy-key.enc -out ssp-operator-deploy-key -d

