apiVersion: v1
kind: Template
metadata:
  name: fedora28
  annotations:
    openshift.io/display-name: "Fedora 28 VM"
    description: >-
      This template can be used to create a VM suitable for
      Fedora 28.
      The template assumes that a PVC is available which is providing the
      necessary Fedora disk image.
    tags: "kubevirt,virtualmachine,fedora"
    iconClass: "icon-fedora"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
  labels:
    kubevirt.io/os: fedora28
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachineInstancePreset
  metadata:
    name: fedora28
  spec:
    selector:
      matchLabels:
        kubevirt.io/os: fedora28
    domain:
      cpu:
        cores: 2
      resources:
        requests:
          memory: 2G
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: fedora28
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/os: fedora28
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
              volumeName: rootvolume
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitvolume
parameters:
- description: Name of the new VM
  name: NAME
- description: Name of the PVC with the Fedora image
  name: PVCNAME
