apiVersion: v1
kind: Template
metadata:
  name: rhel7.5
  annotations:
    openshift.io/display-name: "Red Hat Enterprise Linux 7.5 VM"
    description: >-
      This template can be used to create a VM suitable for
      Red Hat Enterprise Linux 7.5.
      The template assumes that a PVC is available which is providing the
      necessary RHEL disk image.
    tags: "kubevirt,virtualmachine,linux,rhel"
    iconClass: "icon-rhel"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachineInstancePreset
  metadata:
    name: rhel7.5
  spec:
    selector:
      matchLabels:
        kubevirt.io/os: rhel7.5
    domain:
      cpu:
        cores: 2
      resources:
        requests:
          memory: 2G
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: rhel7.5
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/os: rhel7.5
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: virtio
              name: rootdisk
              volumeName: rootvolume
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
parameters:
- description: Name of the new VM
  name: NAME
- description: Name of the PVC with the RHEL image
  name: PVCNAME
