apiVersion: v1
kind: Template
metadata:
  name: win2k12r2
  annotations:
    openshift.io/display-name: "Microsoft Windows Server 2012 R2 VM"
    description: >-
      This template can be used to create a VM suitable for
      Microsoft Windows Server 2012 R2.
      The template assumes that a PVC is available which is providing the
      necessary Windows disk image.
    tags: "kubevirt,virtualmachine,windows"
    iconClass: "icon-windows"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/fabiand/common-templates"
    openshift.io/support-url: "https://github.com/fabiand/common-templates/issues"
    template.openshift.io/bindable: "false"
  labels:
    kubevirt.io/os: win2k12r2
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachineInstancePreset
  metadata:
    name: win2k12r2
  spec:
    selector:
      matchLabels:
        kubevirt.io/os: win2k12r2
    domain:
      clock:
        utc: {}
        timer:
          hpet:
            present: false
          pit:
            tickPolicy: delay
          rtc:
            tickPolicy: catchup
          hyperv: {}
      devices: {}
      features:
        acpi: {}
        apic: {}
        hyperv:
          relaxed: {}
          vapic: {}
          spinlocks:
            spinlocks: 8191
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    labels:
      kubevirt.io/os: win2k12r2
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        labels:
          kubevirt.io/os: win2k12r2
          kubevirt.io/size: large
      spec:
        domain:
          devices:
            disks:
            - disk:
                bus: sata
              name: rootdisk
              volumeName: rootvolume
            interfaces:
            - bridge: {}
              model: e1000
              name: default
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootvolume
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        networks:
        - name: default
          pod: {}
parameters:
- name: NAME
  description: Name of the new VM
  generate: expression
  from: "windows2012r2-[a-z0-9]{6}"
  required: true
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true
